name: Build pour cPanel

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Installation des dépendances
        run: npm install

      - name: Build de l'application
        run: npm run build

      - name: Organisation des fichiers
        run: |
          mkdir -p deploy/.next
          # Copie le coeur de l'application
          cp -r .next/standalone/. deploy/
          # Copie les fichiers statiques (CSS/JS)
          cp -r .next/static deploy/.next/static
          # Copie le dossier public seulement s'il existe
          if [ -d "public" ]; then cp -r public deploy/public; fi
          # Copie les fichiers de config
          cp package.json deploy/
          cp next.config.js deploy/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gsi-smartpay-build
          path: deploy/
          include-hidden-files: true
